"""add field leaks

Revision ID: 29c9d9590a16
Revises: bc8075fd2bf0
Create Date: 2024-05-30 21:30:29.361191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '29c9d9590a16'
down_revision: Union[str, None] = 'bc8075fd2bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('leaks', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'leaks')
    # ### end Alembic commands ###
